### ISSUE TITLE
Unable to deploy angular project to github pages

### ISSUE THREAD

**Issue by aakashgoyal16** [hexojs/hexo-deployer-git#122]
Cleaning

Fetching origin

Checking out origin/gh-pages

Removing files

Copying files

Adding all

Committing

Pushing

*** An error occurred!

{ ProcessError: fatal: AggregateException encountered.
   One or more errors occurred.
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': Invalid argument

    at ChildProcess.<anonymous> (C:\Users\HP\AppData\Roaming\npm\node_modules\angular-cli-ghpages\node_modules\gh-pages\lib\git.js:47:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  code: 128,
  message: 'fatal: AggregateException encountered.\n   One or more errors occurred.\r\nbash: /dev/tty: No such device or address\nerror: failed to execute prompt script (exit code 1)\nfatal: could not read Username for \'https://github.com\': Invalid argument\n',
  name: 'ProcessError' }

**Comment by stevenjoezhang** [comment]
There is a discussion about it: #71
I'm closing this issue. Please join the discussion there :)
