### ISSUE TITLE
执行hexo d时报错，提示TypeError [ERR_INVALID_ARG_TYPE]: The "mode" argument must be integer. Received an instance of Object

### ISSUE THREAD

**Issue by xzy57369** [hexojs/hexo-deployer-git#177]
hexo s本地运行正常，但是部署至github时报错。
完整的提示为
```
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError [ERR_INVALID_ARG_TYPE]: The "mode" argument must be integer. Received an instance of Object
    at copyFile (fs.js:1890:10)
    at tryCatcher (/Users/xuziyang/blog/node_modules/bluebird/js/release/util.js:16:23)
    at ret (eval at makeNodePromisifiedEval (/usr/local/lib/node_modules/hexo/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at /Users/xuziyang/blog/node_modules/hexo-deployer-git/node_modules/hexo-fs/lib/fs.js:144:39
    at tryCatcher (/Users/xuziyang/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/xuziyang/blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/xuziyang/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/xuziyang/blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/xuziyang/blog/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/xuziyang/blog/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/Users/xuziyang/blog/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/Users/xuziyang/blog/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/Users/xuziyang/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/xuziyang/blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/xuziyang/blog/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/xuziyang/blog/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/Users/xuziyang/blog/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/Users/xuziyang/blog/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/Users/xuziyang/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/xuziyang/blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/xuziyang/blog/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/xuziyang/blog/node_modules/bluebird/js/release/promise.js:673:18)
```

 package.json:
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "4.2.0"
  },
  "dependencies": {
    "bluebird": "^3.7.2",
    "eslint": "^6.8.0",
    "hexo": "^4.2.0",
    "hexo-abbrlink": "^2.0.5",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-baidu-sitemap": "^0.1.6",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-json-content": "^4.1.6",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-kramed": "^0.1.4",
    "hexo-renderer-mathjax": "^0.6.0",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3",
    "save": "^2.3.3"
  }
}
```

**Comment by stevenjoezhang** [comment]
已知问题，请等待 Hexo 发布下一个版本。
