### ISSUE TITLE
Permission denied when I used ssh

### ISSUE THREAD

**Issue by m80126colin** [hexojs/hexo-deployer-git#19]
As title, I setup my repo with ssh put it failed when I try to deploy at Github ....

```
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    at ChildProcess.<anonymous> (C:\cygwin64\home\user\Github\_hexo\hexo-tag-owl-demo\node_modules\hexo-util\lib\spawn.js:42:17)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

And my config

```
hexo: 3.1.1
os: Windows_NT 10.0.10240 win32 x64
http_parser: 2.5.0
node: 4.2.1
v8: 4.5.103.35
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2d
```

**Comment by Xuanwo** [comment]
`Permission denied (publickey).`

Did you set your key correctly?

**Comment by m80126colin** [comment]
I nedd to set my key into `_config.yml`? ssh works when I push branches manually.

**Comment by leesei** [comment]
Please post deployer-git's config.

You should have put your SSH public key to GitHub.
[Error: Permission denied (publickey) - User Documentation](https://help.github.com/articles/error-permission-denied-publickey/#platform-windows)

**Comment by m80126colin** [comment]
```
deploy:
  type: git
  repo: git@github.com:pcshic/uniDog.git
  branch: gh-pages
```

**Comment by Xuanwo** [comment]
Do you add your key in your ssh-agent?
