### ISSUE TITLE
err: Error: Spawn failed at ChildProcess.<anonymous>

### ISSUE THREAD

**Issue by reinsss** [hexojs/hexo-deployer-git#193]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Question

error message:

```
[master 3d5a622] Site updated: 2020-10-03 20:27:08
 2 files changed, 2 insertions(+), 2 deletions(-)
fatal: could not read Username for 'https://github.com': No such file or directory
FATAL {
  err: Error: Spawn failed
      at ChildProcess.<anonymous> (C:\CODE\blog\node_modules\hexo-deployer-git\node_modules\hexo-util\lib\spawn.js:51:21)
      at ChildProcess.emit (events.js:315:20)
      at ChildProcess.cp.emit (C:\CODE\blog\node_modules\cross-spawn\lib\enoent.js:34:29)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12) {
    code: 128
  }
}
```

I'm pretty new to this. Don't know how to solve it after trying several methods.

## Environment & Settings

**Node.js & npm version**

``` 
Node.js version v12.18.4.
npm version 6.14.6
``` 

**Hexo and Plugin version(`npm ls --depth 0`)**

``` 
hexo version 5.2.0
```

**Comment by stevenjoezhang** [comment]
There is a discussion about it: https://github.com/hexojs/hexo-deployer-git/issues/71
I'm closing this issue. Please join the discussion there :)

**Comment by codefishyyf** [comment]
FATAL {
  err: Error: Spawn failed
      at ChildProcess.<anonymous> (E:\myBlog\codefishyyfBlog\node_modules\hexo-util\lib\spawn.js:51:21)
      at ChildProcess.emit (events.js:375:28)
      at ChildProcess.cp.emit (E:\myBlog\codefishyyfBlog\node_modules\cross-spawn\lib\enoent.js:34:29)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12) {
    code: 128
  }
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html
报了这个错，不知道怎么解决

**Comment by Wakeuppppp** [comment]
I have used many solutions but not worked.
The following method works for me.
**My computer connects my mobile phone's hotspot, and succussed**

**Comment by mcveh** [comment]
Error: Spawn failed
    at ChildProcess.<anonymous> (/data/data/com.termux/files/home/blog/node_modules/hexo-util/lib/spawn.js:51:21)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
emm不知道为什么

**Comment by Wakeuppppp** [comment]
> Error: Spawn failed at ChildProcess. (/data/data/com.termux/files/home/blog/node_modules/hexo-util/lib/spawn.js:51:21) at ChildProcess.emit (node:events:513:28) at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) emm不知道为什么

报错下面还有错误代码, 你没粘贴上来.
你可以试试用手机给电脑开热点, 这对我有用

**Comment by namaemonaishi** [comment]
> Error: Spawn failed at ChildProcess. (/data/data/com.termux/files/home/blog/node_modules/hexo-util/lib/spawn.js:51:21) at ChildProcess.emit (node:events:513:28) at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) emm不知道为什么

可以试试用手机给电脑开热点

**Comment by Jf710001011** [comment]
跟网络有关：打开/关闭代理重试

**Comment by SlientRainyDay** [comment]
> 跟网络有关：打开/关闭代理重试

感谢  有用
