### ISSUE TITLE
multi git still heve problem~

### ISSUE THREAD

**Issue by Xuanwo** [hexojs/hexo-deployer-git#2]
log from travis-CI is as follow.

```
The command "hexo g" exited with 0.
$ hexo d
INFO  Deploying: git
INFO  Setting up Git deployment...
Initialized empty Git repository in /home/travis/build/Xuanwo/xuanwo.github.io/.deploy_git/.git/
[master (root-commit) e047986] First commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 placeholder
INFO  Clearing .deploy folder...
INFO  Copying files from public folder...
fatal: Unable to create '/home/travis/build/Xuanwo/xuanwo.github.io/.deploy_git/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: fatal: Unable to create '/home/travis/build/Xuanwo/xuanwo.github.io/.deploy_git/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.

    at ChildProcess.<anonymous> (/home/travis/build/Xuanwo/xuanwo.github.io/node_modules/hexo-deployer-git/node_modules/hexo-util/lib/spawn.js:42:17)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)

The command "hexo d" exited with 1.

Done. Your build exited with 1.
```

---
I think we don't need to create a new dir, just add a new remote in git.

add this for every git address:
```
script:
- git push git@github.com:Xuanwo/xuanwo.github.io.git master:master --force
- git push git@gitcafe.com:xuanwo/xuanwo.git master:gitcafe-pages --force

addons:
  ssh_known_hosts:
  - github.com
  - gitcafe.com
```

---
Well, I'm try to fix it by myself. But according to I have no experience in js, it may take some time, sorry for all.

**Comment by Xuanwo** [comment]
I have a ugly idea that we can just del the index.lock.= =

**Comment by Xuanwo** [comment]
Well, I find it works well in my own computer- -.
So, I need to find out what problems in travis.
