### ISSUE TITLE
src must be a string or object describing the source

### ISSUE THREAD

**Issue by gurrrung** [hexojs/hexo-deployer-git#206]
When I run `hexo deploy` I get:
```
gurrrung@gurrrung:~/blog$ hexo deploy
INFO  Validating config
INFO  Deploying: git
FATAL {
  err: Error: src must be a string or an object describing the source
      at Template.init (/home/gurrrung/fun/blog/node_modules/nunjucks/src/environment.js:502:13)
      at Template.Obj (/home/gurrrung/fun/blog/node_modules/nunjucks/src/object.js:62:15)
      at new Template (/home/gurrrung/fun/blog/node_modules/nunjucks/src/environment.js:478:18)
      at Environment.renderString (/home/gurrrung/fun/blog/node_modules/nunjucks/src/environment.js:379:16)
      at Object.renderString (/home/gurrrung/fun/blog/node_modules/nunjucks/index.js:99:14)
      at commitMessage (/home/gurrrung/fun/blog/node_modules/hexo-deployer-git/lib/deployer.js:153:19)
      at Hexo.module.exports (/home/gurrrung/fun/blog/node_modules/hexo-deployer-git/lib/deployer.js:26:19)
      at Hexo.tryCatcher (/home/gurrrung/fun/blog/node_modules/bluebird/js/release/util.js:16:23)
      at Hexo.<anonymous> (/home/gurrrung/fun/blog/node_modules/bluebird/js/release/method.js:15:34)
      at /home/gurrrung/fun/blog/node_modules/hexo/lib/plugins/console/deploy.js:53:20
      at tryCatcher (/home/gurrrung/fun/blog/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (/home/gurrrung/fun/blog/node_modules/bluebird/js/release/reduce.js:166:18)
      at Object.gotAccum (/home/gurrrung/fun/blog/node_modules/bluebird/js/release/reduce.js:155:25)
      at Object.tryCatcher (/home/gurrrung/fun/blog/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/gurrrung/fun/blog/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/home/gurrrung/fun/blog/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (/home/gurrrung/fun/blog/node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (/home/gurrrung/fun/blog/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (/home/gurrrung/fun/blog/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/home/gurrrung/fun/blog/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/home/gurrrung/fun/blog/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:456:21)
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html
```

**Comment by gurrrung** [comment]
I was doing:
```
deploy:
  type: git
  repo:  https://github.com/gurrrung/blog
  branch: [gh-pages]
```
Unwanted square brackets around branch name.
