### ISSUE TITLE
Error in windows env.

### ISSUE THREAD

**Issue by Moln** [hexojs/hexo-deployer-git#81]
这个支持 windows 环境么? win下执行出错!

~~~shell
> hexo deploy
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
INFO  Copying files from extend dirs...
On branch master
nothing to commit, working tree clean
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No error
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/do
cs/troubleshooting.html
Error: bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No error

    at ChildProcess.<anonymous> (D:\www\xxx.github.io\node_modules\hexo-ut
il\lib\spawn.js:37:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (D:\www\xxx.github.io\node_modules\cross-spawn
\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
~~~

**Comment by NoahDragon** [comment]
请设置好git的环境变量，如username，email等。
