### ISSUE TITLE
Hexo can't deploy

### ISSUE THREAD

**Issue by Mr-LiuDC** [hexojs/hexo-deployer-git#93]
When I use command：hexo g -d

and got this error：

packet_write_wait: Connection to 192.30.255.113: Broken pipe
fatal: sha1 file '<stdout>' write error: Broken pipe
fatal: The remote end hung up unexpectedly
error: failed to push some refs to 'git@github.com:Mr-LiuDC/mr-liudc.github.io.git'
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: packet_write_wait: Connection to 192.30.255.113: Broken pipe
fatal: sha1 file '<stdout>' write error: Broken pipe
fatal: The remote end hung up unexpectedly
error: failed to push some refs to 'git@github.com:Mr-LiuDC/mr-liudc.github.io.git'

    at ChildProcess.<anonymous> (D:\Code\Hexo\hexo-blog\liudecai.coding.me-data\liudecai.coding.me\node_modules\hexo-util\lib\spawn.js:37:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (D:\Code\Hexo\hexo-blog\liudecai.coding.me-data\liudecai.coding.me\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)

How can I solve this problem.

**Comment by NoahDragon** [comment]
From the error message, it looks like the remote server doesn't respond.

**Comment by Mr-LiuDC** [comment]
Yea，I see , because of the network.

**Comment by NoahDragon** [comment]
Got it. Is it resolved? If so, could you please close the issue?
