### ISSUE TITLE
安装hexo-deployer-git成功后，调用hexo deploy 命令，提示Local hexo not found in ~/XXX

### ISSUE THREAD

**Issue by JasonQB** [hexojs/hexo-deployer-git#95]
Hexo 安装成功后，next主题也安装好了，`hexo s -g`命令后查看一切OK，然后准备安装deploy相关操作就出现问题了。
$ npm install hexo-deployer-git --save

```
npm WARN deprecated swig@1.4.2: This package is no longer maintained
npm WARN gentlyRm not removing /Users/personal/MyBlog/node_modules/.bin/hexo as it wasn't installed by /Users/personal/MyBlog/node_modules/hexo
npm WARN gentlyRm not removing /Users/personal/MyBlog/node_modules/.bin/rimraf as it wasn't installed by /Users/personal/MyBlog/node_modules/rimraf
npm WARN gentlyRm not removing /Users/personal/MyBlog/node_modules/.bin/nopt as it wasn't installed by /Users/personal/MyBlog/node_modules/nopt
npm WARN gentlyRm not removing /Users/personal/MyBlog/node_modules/.bin/esparse as it wasn't installed by /Users/personal/MyBlog/node_modules/esprima
npm WARN gentlyRm not removing /Users/personal/MyBlog/node_modules/.bin/esvalidate as it wasn't installed by /Users/personal/MyBlog/node_modules/esprima

> fsevents@1.1.3 install /Users/personal/MyBlog/node_modules/fsevents
> node install

[fsevents] Success: "/Users/personal/MyBlog/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm notice created a lockfile as package-lock.json. You should commit this file.
+ hexo-deployer-git@0.3.1
added 15 packages, removed 259 packages and updated 102 packages in 11.629s
```

$ hexo deploy

```
ERROR Local hexo not found in ~/MyBlog
ERROR Try running: 'npm install hexo --save'
```

当我按照上面提示再次执行`npm install hexo --save` 命令完成后，hexo 的指令操作就会报错，比如generate操作

$ hexo g

```
FATAL Cannot find module '/Users/personal/MyBlog/node_modules/hexo-renderer-marked'
Error: Cannot find module '/Users/personal/MyBlog/node_modules/hexo-renderer-marked'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.resolve (internal/module.js:18:19)
    at /Users/personal/MyBlog/node_modules/hexo/lib/hexo/load_plugins.js:52:24
    at tryCatcher (/Users/personal/MyBlog/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/Users/personal/MyBlog/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/Users/personal/MyBlog/node_modules/bluebird/js/release/promise_array.js:114:31)
    at MappingPromiseArray.init (/Users/personal/MyBlog/node_modules/bluebird/js/release/promise_array.js:78:10)
    at Promise._settlePromise (/Users/personal/MyBlog/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/Users/personal/MyBlog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/personal/MyBlog/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/personal/MyBlog/node_modules/bluebird/js/release/promise.js:638:18)
    at MappingPromiseArray.PromiseArray._resolve (/Users/personal/MyBlog/node_modules/bluebird/js/release/promise_array.js:126:19)
    at MappingPromiseArray._filter (/Users/personal/MyBlog/node_modules/bluebird/js/release/map.js:127:10)
    at MappingPromiseArray._promiseFulfilled (/Users/personal/MyBlog/node_modules/bluebird/js/release/map.js:99:18)
    at Promise._settlePromise (/Users/personal/MyBlog/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/personal/MyBlog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/personal/MyBlog/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/personal/MyBlog/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/personal/MyBlog/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/personal/MyBlog/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/personal/MyBlog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/personal/MyBlog/node_modules/bluebird/js/release/promise.js:614:10)
```

**Comment by NoahDragon** [comment]
一般这个问题是运行`hexo`命令在错误的目录下。可否试下重新生成hexo目录，或者运行`npm install`。

**Comment by dontw** [comment]
我遇到一樣的問題
`npm install hexo-deployer-git --save` 後再 `npm install`
就能正常運行了
